<?php

$cad="defjvb/n";
$cad1= " fp.informatica.iessanjuandelacruz@educa.madrid.org ";
$cad2= "educa.madrid.org";
$cad3="defghijk/n";
$cad4="defghi";
$cad5= 'path=[“\usr\$usuario”]|\usr';
$cad6= "C/ Claveles 23,20D,28033,Madrid";
$cad7= "juan rodríguez Hernández";
$long=15;
$car1='.';
$car2='*';

print_r(addslashes($cad5));
echo"<br/>";
print_r(quotemeta($cad3));
echo"<br/>";
print_r(trim($cad1));
echo"<br/>";
print_r(chop($cad3));
echo"<br/>";
print_r(chr(45));
echo"<br/>";
print_r(strlen($cad6));
echo"<br/>";
print_r(strchr($cad1,$car1));
echo"<br/>";
print_r(str_pad($cad4,$long,$car1,STR_PAD_RIGHT));
echo"<br/>";
print_r(str_pad($cad3,-2,$car2,STR_PAD_BOTH));
echo"<br/>";
print_r(strrchr($cad6,','));
echo"<br/>";
print_r(ucwords($cad7));
echo"<br/>";
print_r(substr($cad1,-9));
echo"<br/>";
print_r(strstr($cad6, 'claveles'));
echo"<br/>";
print_r(stristr($cad6, 'claveles'));
echo"<br/>";
print_r(str_repeat($cad4,6));
echo"<br/>";
print_r(count_chars($cad2,3));
echo"<br/>";
print_r(strpos($cad1,".i", 2));
echo"<br/>";
print_r(strrpos($cad1,'i'));
echo"<br/>";
print_r(strstr($cad1,'@'));
echo"<br/>";
print_r(strncmp($cad3,$cad,4));
echo"<br/>";
print_r(quotemeta($cad5));
echo"<br/>";
print_r(strcmp(strstr($cad1,'@'), $cad2));
echo"<br/>";
print_r(strrev($cad3));
echo"<br/>";
print_r(strtr("fp","FP", $cad1));
echo"<br/>";
print_r(strcmp($cad3,$cad4));
echo"<br/>";
print_r(strnatcmp($cad3,$cad4));
echo"<br/>";
print_r(substr($cad1, 15, -16));
echo"<br/>";
print_r(strcspn($cad6,"20D"));
echo"<br/>";